In [26]:
#prefills 

In [27]:
import numpy as np
arr1=np.zeros((3,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
arr2=np.ones((2,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
arr3=np.full((3,4),100)
print(arr3.shape,arr3)


(3, 4) [[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
#some prop
'''arr.shape,size,dtype,ndim,astype'''